# Generated by Django 5.2.3 on 2025-07-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthlog',
            name='target_calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthlog',
            name='target_sleep',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthlog',
            name='target_steps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthlog',
            name='target_water_intake',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='sleep_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='steps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='water_intake',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
